---
kind: pipeline
type: kubernetes
name: terraforn

steps:
- name: version
  image: b2c2ltd/terragrunt:0.0.8
  settings:
    commands:
    - terraform version
  when:
    event: push
- name: help
  image: b2c2ltd/terragrunt:0.0.8
  settings:
    commands:
    - terraform --help
  when:
    event: push

---
kind: pipeline
type: kubernetes
name: terragrunt

steps:
- name: version
  image: b2c2ltd/terragrunt:0.0.8
  settings:
    commands:
    - terragrunt --version
  when:
    event: push
