kind: pipeline
name: terragrunt

steps:
- name: version
  image: b2c2ltd/terragrunt:0.0.8
  settings:
    commands:
    - terragrunt --version
  when:
    event: push
- name: help
  image: b2c2ltd/terragrunt:0.0.8
  settings:
    commands:
    - terragrunt --help
  when:
    event: push
---
kind: pipeline
name: test

steps:
- name: version
  image: b2c2ltd/terragrunt:0.0.8
  settings:
    commands:
    - terragrunt --version
  when:
    event: push
